// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// csound_impl
int csound_impl(String orchestra, String score, String options);
RcppExport SEXP rsound_csound_impl(SEXP orchestraSEXP, SEXP scoreSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< String >::type orchestra(orchestraSEXP);
    Rcpp::traits::input_parameter< String >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< String >::type options(optionsSEXP);
    __result = Rcpp::wrap(csound_impl(orchestra, score, options));
    return __result;
END_RCPP
}
