# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib rsound
#' @export
csound_impl <- function(orchestra, score, options) {
    .Call('rsound_csound_impl', PACKAGE = 'rsound', orchestra, score, options)
}

