# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csound <- function(orchestra, score) {
    .Call('rsound_csound', PACKAGE = 'rsound', orchestra, score)
}

